version: "3.8"
services:
    app:
        build: .
        ports:
            - 3000:3000
        volumes:
            - .:/code
        env_file:
            - .env
        restart: always
        depends_on:
            - ollama
        networks:
            - ollama-docker

    ollama:
        image: ollama/ollama:latest
        ports:
            - 7869:11434
        volumes:
            - .:/code
            - ./ollama/ollama:/root/.ollama
        container_name: ollama
        pull_policy: always
        tty: true
        restart: always
        environment:
            - OLLAMA_KEEP_ALIVE=24h
            - OLLAMA_HOST=0.0.0.0
        networks:
            - ollama-docker

networks:
    ollama-docker:
        external: false
